name: Reminder Cron Job

on:
  schedule:
    # 10分ごとに実行（UTCタイム）
    - cron: "*/10 * * * *"
  workflow_dispatch: # 手動実行も可能

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Cron Endpoint
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            https://kiokkyu.vercel.app/api/cron
